### ISSUE TITLE
[eFEAT] put last match information in both squad and Lineup tables

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#461]
**Is your feature request related to a problem? Please describe.**

For friendlies, I want to make sure I am not overlooking a player that hasn't played recently, and therefore hasn't received training.  It'd be good to add the last played date as a column in the Lineup table (the training indicator is great, but I still would like to know how long some players have not played,  they could be prime sacking candidates)

**Describe the solution you'd like**

 A new column in the Lineup table with the date of the last played game.

**Additional context**
N/A

Next steps before closing the issue (edited by @akasolace ):

 - [ ] the new column need to be visible by default otherwise users won't find about it
 - [ ] add links to player rows in lineup and squad tab (#609)
 - [ ] I would put the new column on the left (maybe after best position)  (can be done as part of  #484)
 - [ ] remove rating column (to be tackled by #610)

**Comment by akasolace** [comment]
@tychobrailleur for my info is that an info available by hrf direclty or should it be calculated ?

**Comment by tychobrailleur** [comment]
I am not sure whether it is in the HRF, but according to CHPP docs it can be found in playerdetails as part of the `LastMatch` field.

**Comment by akasolace** [comment]
@tychobrailleur sorry was a typo I meant CHPP...

**Comment by wsbrenk** [comment]
@tychobrailleur According to the chpp documentation, this information should also be available in the players file, which is already downloaded by HO. We could add those information to the database and to the player overview panel.

**Comment by steffanots** [comment]
Last match is last match in HT. I think it's an irrelevant type of match (league, cup, friendly, duel or preparation). I don't know that we want this.
I add last match into Player Detail with link on match.
I add columns into players tab and lineup tab.
I add property into english.properties.

Because I have problem with loading matches (create repo with bug) , I need help. 
I need master and my branch in new repo to finish testing.

![image](https://user-images.githubusercontent.com/64475678/81229070-8506ea00-8fef-11ea-9674-632035f6c7cc.png)

**Comment by akasolace** [comment]
It is is linked to #485

**Comment by akasolace** [comment]
#485 introduced the following: 

![image](https://user-images.githubusercontent.com/1136496/81501601-9561e200-92d9-11ea-9a92-17a716526d4f.png)

Current ticket is for including these information inside both Lineup and Squad tables replacing existing Rating information


This would summarize all in we want in a single place. In the column, I guess we could here also introduce 3 clicks sort (date defaults, rating and match type)

**Comment by tychobrailleur** [comment]
> Current ticket is for including these information inside both Lineup and Squad tables replacing existing Rating information

Correct – the Lineup tab is where this piece of info would be the most useful to me.

In the table it would probably make more sense to separate those details in their own column to be able to sort ascending/descending on each of them.

**Comment by akasolace** [comment]
@tychobrailleur this is why I suggested 3 click sort ... 

> Ideally the column would accept 3 clicks sort (date defaults, rating and match type)


what do you think, you still prefer 3 differents columns ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur this is why I suggested 3 click sort ...

As far as I understand 3-click sort, it works by sorting on a main value _v_ ASC, then _v_ DESC (or vice-versa), and then another value _w_ (ASC) on the third click.  So you'd only be able to sort on one value asc and desc + another value in a fixed direction.

**Comment by akasolace** [comment]
yes you are right

**Comment by akasolace** [comment]
hi @steffanots are you planning to also take care of this one which also relates to last match ?

**Comment by steffanots** [comment]
As far as I understand you think you need to add 3 columns (date, match and rating).
I think that there should be one column and the varieties according to the date of the match. When the date is clicked, it is already a type of match and I think that sorting by rating does not make sense

**Comment by steffanots** [comment]
take

**Comment by tychobrailleur** [comment]
> @tychobrailleur @akasolace
> When the date is clicked, it is already a type of match 

I am not sure I understand what you mean here?

> and I think that sorting by rating does not make sense

I can think of a situation where I would sort by rating to order players in the same position, and check out which ones have performed better.

I am happy to have one column for now with 3-click sort, we can re-visit later if this is not enough.

**Comment by steffanots** [comment]
![image](https://user-images.githubusercontent.com/64475678/85225236-efbd8a80-b3cf-11ea-9123-19df1882845d.png)

**Comment by steffanots** [comment]
> I am happy to have one column for now with 3-click sort, we can re-visit later if this is not enough.
rating, type and date?

My thinking is sorting by type is unnecessary because what am I going to compare the grade, what if the form, condition and/or skill have changed in a week?
Example, picture up and marker player and player above

**Comment by akasolace** [comment]
@steffanots  just to be sure you are proposing just to rank by match date, right ?

**Comment by steffanots** [comment]
> @steffanots just to be sure you are proposing just to rank by match date, right ?
Yes, column is the last match.

**Comment by akasolace** [comment]
@steffanots   fine for me  (I can aslo see advantages to the simple sort rule)

**Comment by steffanots** [comment]
LastMatch column (date + rating) order by date, rating

**Comment by steffanots** [comment]
Resolve bug on PlayerDetailPanel ... clear add before set last match info

**Comment by akasolace** [comment]
@tychobrailleur this is merged into master. IF you can check whether or not we can close this issue ....
I created #609  and #610 which are related and have not been tackled yet. We could treat them with separate PRs

@steffanots  thank you for the PR

**Comment by akasolace** [comment]
@steffanots  I just tested it and I don't see anything ...

![image](https://user-images.githubusercontent.com/1136496/85430761-da3b9280-b580-11ea-8440-8c903c2e4fd4.png)

**Comment by akasolace** [comment]
Next steps before closing the issue:

 - [ ] the new column need to be visible by default otherwise users won't find about it
 - [ ] add links to player rows in lineup and squad tab (#609)
 - [ ] I would put the new column on the left (maybe after best position)  (can be done as part of  #484)
 - [ ] remove rating column (to be tackled by #610)

**Comment by akasolace** [comment]
I tested it and it is working just fine ...
